/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest6;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author acer
 */
public class FormRumahSakit extends javax.swing.JFrame {
private DefaultTableModel model;
private Connection con = koneksi.getConnection();
private Statement stt;
private ResultSet rss;

 
    /**
     * Creates new form FormRumahSakit
     */
    public FormRumahSakit() {
        initComponents();
    }
    private void InitTable(){
            model = new DefaultTableModel();
            
            model.addColumn("NAMA");
            model.addColumn("TANGGAL LAHIR");
            model.addColumn("USIA");
            model.addColumn("JENIS KELAMIN");
            model.addColumn("DIAGNOSA");
            model.addColumn("DOKTER");
            model.addColumn("RUANGAN");
            model.addColumn("TANGGAL MASUK");

            jTable1.setModel(model);
    }
    
     private void TampilData(){
        try{
            String sql = "SELECT * FROM rumahsakit";
            stt = con.createStatement();
            rss = stt.executeQuery(sql);
            while(rss.next()){
                Object[] o = new Object[8];
                
                o[0] = rss.getString("nama_pasien");
                o[1] = rss.getDate("tl");
                o[2] = rss.getInt("usia");
                o[3] = rss.getString("jk");
                o[4] = rss.getString("diagnosa");
                o[5] = rss.getString("dokter");
                o[6] = rss.getString("ruangan");
                o[7] = rss.getDate("tgl_masuk");
                model.addRow(o);
            }
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
     
     private void TambahData(String nama_pasien, String tanggal, int usia, String jk, String diagnosa, String dokter, String ruangan, String tanggalmasuk){
         
        try{
            String sql = "INSERT INTO rumahsakit VALUES(NULL,'"+nama_pasien+"','"+tanggal+"', '"+usia+"','"+jk+"','"+diagnosa+"','"+dokter+"','"+ruangan+"','"+tanggalmasuk+"')";
            stt = con.createStatement();
            stt.executeUpdate(sql);
            model.addRow(new Object[]{nama_pasien,tanggal , usia, jk, diagnosa, dokter, ruangan, tanggalmasuk});
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
     public void cekstatus(){
         if(tfNama.getText().length()==0||tfTanggal.getText().length()==0||
                tfUsia.getText().length()==0||tfDokter.getText().length()==0||
                tfRuangan.getText().length()==0||tfTanggalmasuk.getText().length()==0||
//                (rbLaki.isSelected()==false && rbPerempuan.isSelected()==false)||
                !(tfTanggal.getText().length()==10)||!(tfTanggalmasuk.getText().length()==10)){
            btnSimpan.setEnabled(false);
        }
        else{
            btnSimpan.setEnabled(true);
        }
     }
     public void bersihkan(){
        tfNama.setText("");        
        tfTanggal.setText("");
        tfUsia.setText("");
        tfDokter.setText("");
        tfRuangan.setText("");       
        tfTanggalmasuk.setText("");
        buttonGroup1.clearSelection();
        lDiagnosa.clearSelection();
        tfCari.setText("");
        cbCari.setSelectedItem("Cari Berdasarkan");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnTambah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnDaftar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PnKeluar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        LayerTambahData = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfUsia = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        tfDokter = new javax.swing.JTextField();
        tfRuangan = new javax.swing.JTextField();
        tfTanggalmasuk = new javax.swing.JTextField();
        tfTanggal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lDiagnosa = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        LayerDaftarPasien = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        cbCari = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        pnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnTambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnTambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnTambahMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest6/img/1491446311_Create.png"))); // NOI18N
        jLabel2.setText("Tambah Data");

        javax.swing.GroupLayout pnTambahLayout = new javax.swing.GroupLayout(pnTambah);
        pnTambah.setLayout(pnTambahLayout);
        pnTambahLayout.setHorizontalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTambahLayout.setVerticalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pnDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnDaftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnDaftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnDaftarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDaftarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnDaftarMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest6/img/1491446378_List.png"))); // NOI18N
        jLabel3.setText("Daftar Pasien");

        javax.swing.GroupLayout pnDaftarLayout = new javax.swing.GroupLayout(pnDaftar);
        pnDaftar.setLayout(pnDaftarLayout);
        pnDaftarLayout.setHorizontalGroup(
            pnDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDaftarLayout.setVerticalGroup(
            pnDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnKeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PnKeluarMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest6/img/1491446440_Exit.png"))); // NOI18N
        jLabel4.setText("Keluar");

        javax.swing.GroupLayout PnKeluarLayout = new javax.swing.GroupLayout(PnKeluar);
        PnKeluar.setLayout(PnKeluarLayout);
        PnKeluarLayout.setHorizontalGroup(
            PnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnKeluarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnKeluarLayout.setVerticalGroup(
            PnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(PnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        jPanel7.setLayout(new java.awt.CardLayout());

        LayerTambahData.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Lahir");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usia");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jenis Kelamin");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Diagnosa");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dokter");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ruangan");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tanggal Masuk");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tambah Data Pasien");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tfNama.setText("jTextField1");
        tfNama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfNamaCaretUpdate(evt);
            }
        });

        tfUsia.setText("jTextField2");
        tfUsia.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfUsiaCaretUpdate(evt);
            }
        });

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki-laki");

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        tfDokter.setText("jTextField3");
        tfDokter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfDokterCaretUpdate(evt);
            }
        });

        tfRuangan.setText("jTextField4");
        tfRuangan.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfRuanganCaretUpdate(evt);
            }
        });

        tfTanggalmasuk.setText("jTextField5");
        tfTanggalmasuk.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfTanggalmasukCaretUpdate(evt);
            }
        });
        tfTanggalmasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTanggalmasukKeyTyped(evt);
            }
        });

        tfTanggal.setText("jTextField6");
        tfTanggal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfTanggalCaretUpdate(evt);
            }
        });
        tfTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTanggalKeyTyped(evt);
            }
        });

        lDiagnosa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Batuk", "Sakit Hati", "Sakit Gigi", "Asma", "Flue", "Patah Tulang", "Patah Hati", "Patah Semangat", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lDiagnosa);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("yyyy-mm-dd");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("yyyy-mm-dd");

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 15, 5));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel8.add(btnTambah);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel8.add(btnSimpan);

        javax.swing.GroupLayout LayerTambahDataLayout = new javax.swing.GroupLayout(LayerTambahData);
        LayerTambahData.setLayout(LayerTambahDataLayout);
        LayerTambahDataLayout.setHorizontalGroup(
            LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerTambahDataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LayerTambahDataLayout.createSequentialGroup()
                        .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel10))
                        .addGap(30, 30, 30)
                        .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LayerTambahDataLayout.createSequentialGroup()
                                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(LayerTambahDataLayout.createSequentialGroup()
                                        .addComponent(rbLaki)
                                        .addGap(31, 31, 31)
                                        .addComponent(rbPerempuan))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerTambahDataLayout.createSequentialGroup()
                                        .addComponent(tfTanggal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addGap(66, 66, 66))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfNama)
                            .addComponent(tfUsia)))
                    .addGroup(LayerTambahDataLayout.createSequentialGroup()
                        .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(23, 23, 23)
                        .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfRuangan)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerTambahDataLayout.createSequentialGroup()
                                    .addComponent(tfTanggalmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17)
                                    .addGap(432, 432, 432))
                                .addComponent(tfDokter)))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(LayerTambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LayerTambahDataLayout.setVerticalGroup(
            LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerTambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(tfUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbLaki)
                        .addComponent(rbPerempuan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayerTambahDataLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(tfDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(tfRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(LayerTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfTanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel7.add(LayerTambahData, "card2");

        LayerDaftarPasien.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Daftar Data Pasien");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest6/img/Find.png"))); // NOI18N
        jLabel15.setText("Cari Data");

        tfCari.setText("jTextField1");
        tfCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCariKeyTyped(evt);
            }
        });

        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cari Berdasarkan", "Pasien", "Dokter" }));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("By");

        javax.swing.GroupLayout LayerDaftarPasienLayout = new javax.swing.GroupLayout(LayerDaftarPasien);
        LayerDaftarPasien.setLayout(LayerDaftarPasienLayout);
        LayerDaftarPasienLayout.setHorizontalGroup(
            LayerDaftarPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerDaftarPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayerDaftarPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(LayerDaftarPasienLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LayerDaftarPasienLayout.setVerticalGroup(
            LayerDaftarPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerDaftarPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LayerDaftarPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(LayerDaftarPasien, "card3");

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest6/img/1491446794_cross_1.png"))); // NOI18N
        jLabel1.setText("Data Rumah Sakit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(682, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Design by 1515015127");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(900, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnKeluarMousePressed
        // TODO add your handling code here:
        PnKeluar.setBackground(Color.ORANGE);
        System.exit(1);
    }//GEN-LAST:event_PnKeluarMousePressed

    private void pnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTambahMouseClicked
        // TODO add your handling code here:
        LayerTambahData.setVisible(true);
        LayerDaftarPasien.setVisible(false);
    }//GEN-LAST:event_pnTambahMouseClicked

    private void pnDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDaftarMouseClicked
        // TODO add your handling code here:
        LayerTambahData.setVisible(false);
        LayerDaftarPasien.setVisible(true);
    }//GEN-LAST:event_pnDaftarMouseClicked

    private void pnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTambahMouseEntered
        // TODO add your handling code here:
        pnTambah.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_pnTambahMouseEntered

    private void pnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTambahMouseExited
        // TODO add your handling code here:
        pnTambah.setBackground(getBackground());
    }//GEN-LAST:event_pnTambahMouseExited

    private void pnDaftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDaftarMouseEntered
        // TODO add your handling code here:
        pnDaftar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_pnDaftarMouseEntered

    private void pnDaftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDaftarMouseExited
        // TODO add your handling code here:
        pnDaftar.setBackground(getBackground());
    }//GEN-LAST:event_pnDaftarMouseExited

    private void PnKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnKeluarMouseEntered
        // TODO add your handling code here:
        PnKeluar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_PnKeluarMouseEntered

    private void PnKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnKeluarMouseExited
        // TODO add your handling code here:
        PnKeluar.setBackground(getBackground());
    }//GEN-LAST:event_PnKeluarMouseExited

    private void pnTambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTambahMousePressed
        // TODO add your handling code here:
        pnTambah.setBackground(Color.ORANGE);
    }//GEN-LAST:event_pnTambahMousePressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         InitTable();
         TampilData();
    }//GEN-LAST:event_formComponentShown

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:        
        if(tfNama.getText().length()==0||tfTanggal.getText().length()==0||
                tfUsia.getText().length()==0||lDiagnosa.isSelectionEmpty()==true ||
                tfDokter.getText().length()==0||tfRuangan.getText().length()==0||
                tfTanggalmasuk.getText().length()==0||(rbLaki.isSelected()==false && rbPerempuan.isSelected()==false)||
                !(tfTanggal.getText().length()==10)||!(tfTanggalmasuk.getText().length()==10)){
            
            JOptionPane.showMessageDialog(null, "Silahkan Isi Semua Data dengan Benar!","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String jk = null;
            String nama_pasien = tfNama.getText();
            String tanggal = tfTanggal.getText();
            int usia = Integer.parseInt(tfUsia.getText());
            if(rbLaki.isSelected()){
                jk = "L";
            }
            else if(rbPerempuan.isSelected()){
                jk = "P";
            }
            
            String diagnosa = lDiagnosa.getSelectedValue();
            String dokter = tfDokter.getText();
            String ruangan = tfRuangan.getText();
            String tanggalmasuk = tfTanggal.getText();
            TambahData(nama_pasien,tanggal,usia,jk,diagnosa,dokter,ruangan,tanggalmasuk);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Disimpan", "Perhatian", WIDTH);
            bersihkan();
        }
            
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        bersihkan();
        
        tfNama.setEnabled(false);
        tfTanggal.setEnabled(false);
        tfUsia.setEnabled(false);
        tfDokter.setEnabled(false);
        tfRuangan.setEnabled(false);
        tfTanggalmasuk.setEnabled(false);
        lDiagnosa.setEnabled(false);
        rbLaki.setEnabled(false);
        rbPerempuan.setEnabled(false);
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tfTanggalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTanggalKeyTyped
        // TODO add your handling code here:
        tfTanggal.addKeyListener(new KeyAdapter(){
             @Override
             public void keyTyped(KeyEvent e){
                 char karakter = e.getKeyChar();
                 if(!((karakter >='0') && (karakter<='9') || (karakter == '\b')||(karakter == '-'))){
                     e.consume();
                 }
             }
        });
    }//GEN-LAST:event_tfTanggalKeyTyped

    private void tfTanggalmasukKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTanggalmasukKeyTyped
        // TODO add your handling code here:
         tfTanggalmasuk.addKeyListener(new KeyAdapter(){
             @Override
             public void keyTyped(KeyEvent e){
                 char karakter = e.getKeyChar();
                 if(!((karakter >='0') && (karakter<='9') || (karakter == '\b')||(karakter == '-'))){
                     e.consume();
                 }
             }
        });
    }//GEN-LAST:event_tfTanggalmasukKeyTyped

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        tfNama.setEnabled(true);
        tfTanggal.setEnabled(true);
        tfUsia.setEnabled(true);
        tfDokter.setEnabled(true);
        tfRuangan.setEnabled(true);
        tfTanggalmasuk.setEnabled(true);
        lDiagnosa.setEnabled(true);
        rbLaki.setEnabled(true);
        rbPerempuan.setEnabled(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tfNamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfNamaCaretUpdate
        // TODO add your handling code here:
        cekstatus();
    }//GEN-LAST:event_tfNamaCaretUpdate

    private void tfTanggalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfTanggalCaretUpdate
        // TODO add your handling code here:
        cekstatus();
    }//GEN-LAST:event_tfTanggalCaretUpdate

    private void tfUsiaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfUsiaCaretUpdate
        // TODO add your handling code here:
        cekstatus();
    }//GEN-LAST:event_tfUsiaCaretUpdate

    private void tfDokterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfDokterCaretUpdate
        // TODO add your handling code here:
       cekstatus();
    }//GEN-LAST:event_tfDokterCaretUpdate

    private void tfRuanganCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfRuanganCaretUpdate
        // TODO add your handling code here:
      cekstatus();
    }//GEN-LAST:event_tfRuanganCaretUpdate

    private void tfTanggalmasukCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfTanggalmasukCaretUpdate
        // TODO add your handling code here:
      cekstatus();
    }//GEN-LAST:event_tfTanggalmasukCaretUpdate

    private void tfCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariKeyTyped
        // TODO add your handling code here:
        if(cbCari.getSelectedItem().equals("Cari Berdasarkan")){
             JOptionPane.showMessageDialog(null, "Pilih Filter Pencarian","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        DefaultTableModel model1 = new DefaultTableModel();
        String cariapa;
        if(cbCari.getSelectedItem().toString()=="Pasien"){
            cariapa = "nama_pasien";
        }
        else{
            cariapa = "dokter";
        }
        try{
            String sql = "Select * from rumahsakit where "+cariapa+" like '%" + tfCari.getText() + "%'";
            stt = con.createStatement();
            rss = stt.executeQuery(sql);
            model.setRowCount(0);
            Object[] o = new Object[8];
            int x = 1;
            while(rss.next()){
                o[0] = rss.getString("nama_pasien");
                o[1] = rss.getDate("tl");
                o[2] = rss.getInt("usia");
                o[3] = rss.getString("jk");
                o[4] = rss.getString("diagnosa");
                o[5] = rss.getString("dokter");
                o[6] = rss.getString("ruangan");
                o[7] = rss.getDate("tgl_masuk");
                model.addRow(o);
                x++;
            }
            rss.close();
            stt.close();
                }catch (SQLException e){
                    System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_tfCariKeyTyped

    private void pnTambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTambahMouseReleased
        // TODO add your handling code here:
        pnTambah.setBackground(getBackground());
    }//GEN-LAST:event_pnTambahMouseReleased

    private void pnDaftarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDaftarMousePressed
        // TODO add your handling code here:
        pnDaftar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_pnDaftarMousePressed

    private void pnDaftarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDaftarMouseReleased
        // TODO add your handling code here:
        pnDaftar.setBackground(getBackground());
    }//GEN-LAST:event_pnDaftarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRumahSakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayerDaftarPasien;
    private javax.swing.JPanel LayerTambahData;
    private javax.swing.JPanel PnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lDiagnosa;
    private javax.swing.JPanel pnDaftar;
    private javax.swing.JPanel pnTambah;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfDokter;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfRuangan;
    private javax.swing.JTextField tfTanggal;
    private javax.swing.JTextField tfTanggalmasuk;
    private javax.swing.JTextField tfUsia;
    // End of variables declaration//GEN-END:variables
}
