/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest2;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class FormKTP extends javax.swing.JFrame {

    /**
     * Creates new form FormKTP
     */
    public FormKTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFTempat = new javax.swing.JTextField();
        TFAlamat = new javax.swing.JTextField();
        TFRT = new javax.swing.JTextField();
        TFDesa = new javax.swing.JTextField();
        TFKecamatan = new javax.swing.JTextField();
        RBWNI = new javax.swing.JRadioButton();
        RBWNA = new javax.swing.JRadioButton();
        DCTanggal = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        RBLaki = new javax.swing.JRadioButton();
        RBPerempuan = new javax.swing.JRadioButton();
        CBAgama = new javax.swing.JComboBox<>();
        CBKawin = new javax.swing.JComboBox<>();
        TFPekerjaan = new javax.swing.JTextField();
        BSubmit = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel1 = new usu.widget.Panel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CBGolDar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        TFRW = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        TFPesan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 138, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tempat/Tgl Lahir");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 165, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 201, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 262, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RT/ RW");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kel/ Desa");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 321, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kecamatan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 351, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Agama");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 382, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status Perkawinan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 412, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pekerjaan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 443, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kewarganegaraan");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 475, -1, -1));
        jPanel1.add(TFNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 134, 257, -1));
        jPanel1.add(TFTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 165, 131, -1));
        jPanel1.add(TFAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 258, 257, -1));
        jPanel1.add(TFRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 289, 110, -1));
        jPanel1.add(TFDesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 320, 257, -1));

        TFKecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFKecamatanActionPerformed(evt);
            }
        });
        jPanel1.add(TFKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 351, 257, -1));

        RBWNI.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup2.add(RBWNI);
        RBWNI.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        RBWNI.setForeground(new java.awt.Color(255, 255, 255));
        RBWNI.setText("WNI");
        jPanel1.add(RBWNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        RBWNA.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup2.add(RBWNA);
        RBWNA.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        RBWNA.setForeground(new java.awt.Color(255, 255, 255));
        RBWNA.setText("WNA");
        RBWNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBWNAActionPerformed(evt);
            }
        });
        jPanel1.add(RBWNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        DCTanggal.setBackground(new java.awt.Color(0, 153, 153));
        DCTanggal.setDateFormatString("dd-MM-yyyy");
        DCTanggal.setMaxSelectableDate(new java.util.Date(253370739672000L));
        DCTanggal.setMinSelectableDate(new java.util.Date(-62135794728000L));
        jPanel1.add(DCTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 165, 102, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("/");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 167, 10, -1));

        RBLaki.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBLaki);
        RBLaki.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        RBLaki.setForeground(new java.awt.Color(255, 255, 255));
        RBLaki.setText("Laki-Laki");
        RBLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBLakiActionPerformed(evt);
            }
        });
        jPanel1.add(RBLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        RBPerempuan.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(RBPerempuan);
        RBPerempuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        RBPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        RBPerempuan.setText("Perempuan");
        RBPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPerempuanActionPerformed(evt);
            }
        });
        jPanel1.add(RBPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        CBAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Agama", "Islam", "Protestan", "Katolik", "Hindu", "Budha", "Khonghucu" }));
        jPanel1.add(CBAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 382, 135, -1));

        CBKawin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status Perkawinan", "Belum Kawin", "Kawin" }));
        jPanel1.add(CBKawin, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 408, -1, -1));
        jPanel1.add(TFPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 439, 257, -1));

        BSubmit.setText("Submit");
        BSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(BSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 502, 117, -1));

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        jPanel1.add(BReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 502, 134, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 543, 958, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 958, -1));

        panel1.setBackground(new java.awt.Color(0, 153, 153));
        panel1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/Posttest2/bg-header.png"))); // NOI18N
        panel1.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_RIGHT_MIDDLE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bebas Neue Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 958, 70));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 958, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Golongan Darah");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 228, -1, -1));

        CBGolDar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Golongan Darah", "A", "B", "O", "AB" }));
        CBGolDar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBGolDarActionPerformed(evt);
            }
        });
        jPanel1.add(CBGolDar, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 228, 131, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("/");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 291, 10, -1));
        jPanel1.add(TFRW, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 289, 120, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        TAHasil.setEditable(false);
        TAHasil.setColumns(20);
        TAHasil.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        TAHasil.setRows(5);
        TAHasil.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TAHasil.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(TAHasil);

        TFPesan.setEditable(false);
        TFPesan.setBackground(new java.awt.Color(51, 51, 51));
        TFPesan.setFont(new java.awt.Font("Balls on the rampage", 0, 32)); // NOI18N
        TFPesan.setForeground(new java.awt.Color(255, 0, 0));
        TFPesan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFPesan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TFPesan.setFocusable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(TFPesan))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 460, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBGolDarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBGolDarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBGolDarActionPerformed

    private void BSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSubmitActionPerformed
        // TODO add your handling code here:
        String Nama, Tempat, JK, GolDar, Alamat, RT,RW, Desa, Kecamatan, Agama, Skawin, Pekerjaan, KWGR;
        Date TglLahir;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Nama = TFNama.getText();
        Tempat = TFTempat.getText();
        TglLahir = DCTanggal.getDate();
        if(RBLaki.isSelected()){
            JK = RBLaki.getText();
        }
        else{
            JK = RBPerempuan.getText();
        }
        GolDar = CBGolDar.getSelectedItem().toString();
        Alamat = TFAlamat.getText();
        RT = TFRT.getText();
        RW = TFRW.getText();
        Desa = TFDesa.getText();
        Kecamatan = TFKecamatan.getText();
        Agama = CBAgama.getSelectedItem().toString();
        Skawin = CBKawin.getSelectedItem().toString();
        Pekerjaan = TFPekerjaan.getText();
        if(RBWNI.isSelected()){
            KWGR = RBWNI.getText();
        }
        else{
            KWGR = RBWNA.getText();
        }
        
        if((TFNama.getText().length() == 0 )|| 
                (TFTempat.getText().length() == 0 )|| 
                (CBGolDar.getSelectedItem().toString().length() == 20)||
                (DCTanggal.getDate()==null)||
                (buttonGroup1.getSelection()==null)||
                (buttonGroup2.getSelection()==null)||
                (TFAlamat.getText().length()==0)||
                (TFRT.getText().length()==0)||
                (TFRW.getText().length()==0)||
                (TFDesa.getText().length()==0)||
                (TFKecamatan.getText().length()==0)||
                (CBAgama.getSelectedItem().toString().length()==11)||
                (CBKawin.getSelectedItem().toString().length()==23)||
                (TFPekerjaan.getText().length()==0)
                ){
            JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            TFPesan.setText("Selamat, Data Anda Berhasil Disimpan");
            TAHasil.setText(
                    "Berikut ini adalah data yang berhasil disimpan pada Sistem Pendaftaran E-KTP"
                            + "\nNama\t\t: "+Nama
                            + "\nTempat,Tgl Lahir\t: "+Tempat+", "+sdf.format(TglLahir)
                            + "\nJenis Kelamin\t\t: "+JK
                            + "\nGolongan Darah\t: "+GolDar
                            + "\nAlamat\t\t: "+Alamat
                            + "\n  RT\t\t: "+RT
                            + "\n  RW\t\t: "+RW
                            + "\n  Desa/Kelurahan\t: "+Desa
                            + "\n  Kecamatan\t\t: "+Kecamatan
                            + "\nAgama\t\t: "+Agama
                            + "\nStatus Kawin\t\t: "+Skawin
                            + "\nPekerjaan\t\t: "+Pekerjaan
                            + "\nKewarganegaraan\t: "+KWGR
                            + "\nBerlaku Hingga\t: Seumur Hidup"
            );
        }
    }//GEN-LAST:event_BSubmitActionPerformed

    private void RBWNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBWNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBWNAActionPerformed

    private void TFKecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFKecamatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFKecamatanActionPerformed

    private void RBLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBLakiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RBLakiActionPerformed

    private void RBPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBPerempuanActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        TFNama.setText("");
        TFTempat.setText("");
        DCTanggal.setDate(null);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        CBGolDar.setSelectedItem("Pilih Golongan Darah");
        TFAlamat.setText("");
        TFRT.setText("");
        TFRW.setText("");
        TFDesa.setText("");
        TFKecamatan.setText("");
        CBAgama.setSelectedItem("Pilih Agama");
        CBKawin.setSelectedItem("Pilih Status Perkawinan");
        TFPekerjaan.setText("");
        TFPesan.setText("");
        TAHasil.setText("");
        
    }//GEN-LAST:event_BResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BReset;
    private javax.swing.JButton BSubmit;
    private javax.swing.JComboBox<String> CBAgama;
    private javax.swing.JComboBox<String> CBGolDar;
    private javax.swing.JComboBox<String> CBKawin;
    private com.toedter.calendar.JDateChooser DCTanggal;
    private javax.swing.JRadioButton RBLaki;
    private javax.swing.JRadioButton RBPerempuan;
    private javax.swing.JRadioButton RBWNA;
    private javax.swing.JRadioButton RBWNI;
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFDesa;
    private javax.swing.JTextField TFKecamatan;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFPekerjaan;
    private javax.swing.JTextField TFPesan;
    private javax.swing.JTextField TFRT;
    private javax.swing.JTextField TFRW;
    private javax.swing.JTextField TFTempat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private usu.widget.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
