/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest4;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class AplikasiPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPelanggan
     */
    public AplikasiPelanggan() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPBeranda = new javax.swing.JPanel();
        jLNama = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        jLTelp = new javax.swing.JLabel();
        TFTelp = new javax.swing.JTextField();
        jLAlamat = new javax.swing.JLabel();
        TFAlamat = new javax.swing.JTextField();
        jLBerat = new javax.swing.JLabel();
        TFBerat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BTNProses = new javax.swing.JButton();
        BTNUlang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAMonitor = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        RBReguler = new javax.swing.JRadioButton();
        RBExpress = new javax.swing.JRadioButton();
        SDiskon = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LPersen = new javax.swing.JLabel();
        jLNama1 = new javax.swing.JLabel();
        TFNama1 = new javax.swing.JTextField();
        jLTelp1 = new javax.swing.JLabel();
        TFTelp1 = new javax.swing.JTextField();
        jLAlamat1 = new javax.swing.JLabel();
        TFAlamat1 = new javax.swing.JTextField();
        jPAbout = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jBHitung = new javax.swing.JButton();
        jBAbout = new javax.swing.JButton();
        jBKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Aplikasi Diskon Pelanggan");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest4/header.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNama.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLNama.setText("Nama Pengirim");
        jPBeranda.add(jLNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 49, -1, -1));

        TFNama.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TFNama.setText("JTextField1");
        TFNama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNamaCaretUpdate(evt);
            }
        });
        TFNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNamaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFNamaKeyReleased(evt);
            }
        });
        jPBeranda.add(TFNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 63, 184, -1));

        jLTelp.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLTelp.setText("No. Telp Pengirim");
        jPBeranda.add(jLTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 88, -1, -1));

        TFTelp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TFTelp.setText("JTextField2");
        TFTelp.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFTelpCaretUpdate(evt);
            }
        });
        TFTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTelpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFTelpKeyReleased(evt);
            }
        });
        jPBeranda.add(TFTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 107, 184, -1));

        jLAlamat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLAlamat.setText("Alamat Pengirim");
        jPBeranda.add(jLAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 132, -1, -1));

        TFAlamat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TFAlamat.setText("JTextField3");
        TFAlamat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFAlamatCaretUpdate(evt);
            }
        });
        TFAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFAlamatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFAlamatKeyReleased(evt);
            }
        });
        jPBeranda.add(TFAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 151, 184, -1));

        jLBerat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLBerat.setText("Berat  Barang");
        jPBeranda.add(jLBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 303, -1, -1));

        TFBerat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TFBerat.setText("0");
        TFBerat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFBeratCaretUpdate(evt);
            }
        });
        TFBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBeratActionPerformed(evt);
            }
        });
        jPBeranda.add(TFBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 322, 78, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Kg");
        jPBeranda.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 325, -1, -1));

        BTNProses.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BTNProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest4/Application.png"))); // NOI18N
        BTNProses.setText("Proses");
        BTNProses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTNProsesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BTNProsesMouseReleased(evt);
            }
        });
        BTNProses.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                BTNProsesComponentHidden(evt);
            }
        });
        BTNProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNProsesActionPerformed(evt);
            }
        });
        jPBeranda.add(BTNProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        BTNUlang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BTNUlang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest4/Refresh.png"))); // NOI18N
        BTNUlang.setText("Ulangi");
        BTNUlang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNUlangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTNUlangMousePressed(evt);
            }
        });
        BTNUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUlangActionPerformed(evt);
            }
        });
        jPBeranda.add(BTNUlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        TAMonitor.setEditable(false);
        TAMonitor.setColumns(20);
        TAMonitor.setRows(5);
        TAMonitor.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(TAMonitor);

        jPBeranda.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 49, 471, 391));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setText("Form Data Pengiriman");
        jPBeranda.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 11, -1, -1));

        buttonGroup1.add(RBReguler);
        RBReguler.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        RBReguler.setText("Reguler");
        jPBeranda.add(RBReguler, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 367, -1, -1));

        buttonGroup1.add(RBExpress);
        RBExpress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        RBExpress.setText("Express");
        jPBeranda.add(RBExpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 367, -1, -1));

        SDiskon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        SDiskon.setMajorTickSpacing(10);
        SDiskon.setPaintLabels(true);
        SDiskon.setPaintTicks(true);
        SDiskon.setValue(0);
        SDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SDiskonStateChanged(evt);
            }
        });
        jPBeranda.add(SDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 169, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Jenis Jasa");
        jPBeranda.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 347, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Atur Diskon");
        jPBeranda.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 395, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPBeranda.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 49, 12, 391));

        LPersen.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LPersen.setForeground(new java.awt.Color(255, 0, 51));
        LPersen.setText("0 %");
        jPBeranda.add(LPersen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 36, 26));

        jLNama1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLNama1.setText("Nama Penerima");
        jPBeranda.add(jLNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 176, -1, -1));

        TFNama1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TFNama1.setText("JTextField4");
        TFNama1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNama1CaretUpdate(evt);
            }
        });
        TFNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNama1ActionPerformed(evt);
            }
        });
        TFNama1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNama1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFNama1KeyReleased(evt);
            }
        });
        jPBeranda.add(TFNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 190, 184, -1));

        jLTelp1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLTelp1.setText("No. Telp Penerima");
        jPBeranda.add(jLTelp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 215, -1, -1));

        TFTelp1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TFTelp1.setText("JTextField5");
        TFTelp1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFTelp1CaretUpdate(evt);
            }
        });
        TFTelp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTelp1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFTelp1KeyReleased(evt);
            }
        });
        jPBeranda.add(TFTelp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 234, 184, -1));

        jLAlamat1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLAlamat1.setText("Alamat Penerima");
        jPBeranda.add(jLAlamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 259, -1, -1));

        TFAlamat1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TFAlamat1.setText("JTextField6");
        TFAlamat1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFAlamat1CaretUpdate(evt);
            }
        });
        TFAlamat1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFAlamat1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFAlamat1KeyReleased(evt);
            }
        });
        jPBeranda.add(TFAlamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 278, 184, -1));

        jPanel2.add(jPBeranda, "card2");

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel25.setText("Aplikasi Tarif Barang LajuiExpress");

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel26.setText("Dikembangkan dan Didesain Oleh :");

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel27.setText("Nama");

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel28.setText("NIM");

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel29.setText("Fakultas");

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel30.setText("Universitas");

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel31.setText(": Muhammad Sarman Noorlah");

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel32.setText(": 1515015127");

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel33.setText(": Fakultas Ilmu Komputer dan Teknologi Informasi");

        jLabel34.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel34.setText(": Universitas Mulawarman");

        javax.swing.GroupLayout jPAboutLayout = new javax.swing.GroupLayout(jPAbout);
        jPAbout.setLayout(jPAboutLayout);
        jPAboutLayout.setHorizontalGroup(
            jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAboutLayout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAboutLayout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel34))
                        .addGroup(jPAboutLayout.createSequentialGroup()
                            .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAboutLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(66, 66, 66))
                                .addGroup(jPAboutLayout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addGap(74, 74, 74)))
                            .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(jLabel31))))
                    .addGroup(jPAboutLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel33)))
                .addGap(129, 129, 129))
        );
        jPAboutLayout.setVerticalGroup(
            jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAboutLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPAbout, "card3");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 127, 800, 490));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Copyright @2017 LajuiExpress");
        jPanel3.add(jLabel13);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 618, 799, 20));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jBHitung.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest4/Accounting.png"))); // NOI18N
        jBHitung.setText("Beranda");
        jBHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBHitungMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBHitungMouseReleased(evt);
            }
        });
        jBHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHitungActionPerformed(evt);
            }
        });
        jPanel5.add(jBHitung);

        jBAbout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest4/About.png"))); // NOI18N
        jBAbout.setText("About");
        jBAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBAboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBAboutMouseReleased(evt);
            }
        });
        jBAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAboutActionPerformed(evt);
            }
        });
        jPanel5.add(jBAbout);

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jBKeluar.setBackground(new java.awt.Color(204, 204, 204));
        jBKeluar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest4/Exit.png"))); // NOI18N
        jBKeluar.setText("Keluar");
        jBKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBKeluarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBKeluarMouseReleased(evt);
            }
        });
        jBKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKeluarActionPerformed(evt);
            }
        });
        jPanel4.add(jBKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHitungActionPerformed
        // TODO add your handling code here:
        jPBeranda.setVisible(true);
        jPAbout.setVisible(false);
    }//GEN-LAST:event_jBHitungActionPerformed

    private void jBAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAboutActionPerformed
        // TODO add your handling code here:
        jPBeranda.setVisible(false);
        jPAbout.setVisible(true);
    }//GEN-LAST:event_jBAboutActionPerformed

    private void TFBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBeratActionPerformed

    private void BTNProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNProsesActionPerformed
        // TODO add your handling code here:
        String nama, nama1, alamat, alamat1, telp, telp1,jasa = null;
        float berat;
        double hasil = 0;
        int diskon;
        nama   = TFNama.getText();
        alamat = TFAlamat.getText();
        telp   = TFTelp.getText();
        
        nama1   = TFNama1.getText();
        alamat1 = TFAlamat1.getText();
        telp1   = TFTelp1.getText();
        
        berat  = Float.parseFloat(TFBerat.getText());
        diskon = SDiskon.getValue();
        if(RBReguler.isSelected()==true){
            jasa = "Reguler";
            hasil  = (11500*berat)-((11500*berat*diskon)/100);
            
        }
        else if(RBExpress.isSelected()==true){
            jasa = "Express";
            hasil  = ((11500*1.5)*berat)-((11500*1.5)*berat*diskon)/100;
        }
        
        if(buttonGroup1.getSelection()==null|| berat<=0){
            JOptionPane.showMessageDialog(null, "Berat tidak boleh 0 dan pilih jasa","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            TAMonitor.setText("==============  DATA PENGIRIMAN BARANG LajuiExpress  ==============\n"+
                "\n---------------------------------------------------------------------------------------------------------------\n"+
                "Data Pengirim\n"+
                "---------------------------------------------------------------------------------------------------------------\n"+
                "Nama\t: "+nama+
                "\nNo. Telepon\t: "+telp+
                "\nAlamat\t: "+alamat+
                
                "\n\n---------------------------------------------------------------------------------------------------------------\n"+
                "Data Penerima\n"+
                "---------------------------------------------------------------------------------------------------------------\n"+
                "Nama\t: "+nama1+
                "\nNo. Telepon\t: "+telp1+
                "\nAlamat\t: "+alamat1+
                
                "\n\n---------------------------------------------------------------------------------------------------------------\n"+
                "Rincian Barang\n"+
                "---------------------------------------------------------------------------------------------------------------"+
                "\nBerat Barang\t: "+berat+" Kg"+
                "\nJenis Jasa\t: "+jasa+
                "\nDiskon\t: "+diskon+"%"+
                "\nBiaya Kirim\t: Rp"+hasil);
        
        }
        
        
        
    }//GEN-LAST:event_BTNProsesActionPerformed

    private void BTNProsesComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BTNProsesComponentHidden
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BTNProsesComponentHidden

    private void SDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SDiskonStateChanged
        // TODO add your handling code here:
        LPersen.setText(String.valueOf(SDiskon.getValue()+"%"));
        
    }//GEN-LAST:event_SDiskonStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jBKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBKeluarActionPerformed

    private void TFNamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNamaCaretUpdate
        // TODO add your handling code here:
        if((TFNama.getText().length() == 0)||
                (TFNama1.getText().length() == 0)||
                (TFAlamat.getText().length() == 0) || 
                (TFAlamat1.getText().length() == 0)||
                (TFTelp.getText().length() == 0)||
                (TFTelp1.getText().length() == 0)||
                (TFBerat.getText().length() == 0)||
                (TFBerat.getText().matches("[0]"))){
            BTNProses.setEnabled(false);
        }
        else{
            BTNProses.setEnabled(true);
        }
            
    }//GEN-LAST:event_TFNamaCaretUpdate

    private void TFTelpCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFTelpCaretUpdate
        // TODO add your handling code here:
        if((TFNama.getText().length() == 0)||
                (TFNama1.getText().length() == 0)||
                (TFAlamat.getText().length() == 0) || 
                (TFAlamat1.getText().length() == 0)||
                (TFTelp.getText().length() == 0)||
                (TFTelp1.getText().length() == 0)||
                (TFBerat.getText().length() == 0)||
                (TFBerat.getText().matches("[0]"))){
            BTNProses.setEnabled(false);
        }
        else{
            BTNProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFTelpCaretUpdate

    private void TFAlamatCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFAlamatCaretUpdate
        // TODO add your handling code here:
        if((TFNama.getText().length() == 0)||
                (TFNama1.getText().length() == 0)||
                (TFAlamat.getText().length() == 0) || 
                (TFAlamat1.getText().length() == 0)||
                (TFTelp.getText().length() == 0)||
                (TFTelp1.getText().length() == 0)||
                (TFBerat.getText().length() == 0)||
                (TFBerat.getText().matches("[0]"))){
            BTNProses.setEnabled(false);
        }
        else{
            BTNProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFAlamatCaretUpdate

    private void TFNama1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNama1CaretUpdate
        // TODO add your handling code here:
        if((TFNama.getText().length() == 0)||
                (TFNama1.getText().length() == 0)||
                (TFAlamat.getText().length() == 0) || 
                (TFAlamat1.getText().length() == 0)||
                (TFTelp.getText().length() == 0)||
                (TFTelp1.getText().length() == 0)||
                (TFBerat.getText().length() == 0)||
                (TFBerat.getText().matches("[0]"))){
            BTNProses.setEnabled(false);
        }
        else{
            BTNProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFNama1CaretUpdate

    private void TFTelp1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFTelp1CaretUpdate
        // TODO add your handling code here:
        if((TFNama.getText().length() == 0)||
                (TFNama1.getText().length() == 0)||
                (TFAlamat.getText().length() == 0) || 
                (TFAlamat1.getText().length() == 0)||
                (TFTelp.getText().length() == 0)||
                (TFTelp1.getText().length() == 0)||
                (TFBerat.getText().length() == 0)||
                (TFBerat.getText().matches("[0]"))){
            BTNProses.setEnabled(false);
        }
        else{
            BTNProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFTelp1CaretUpdate

    private void TFAlamat1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFAlamat1CaretUpdate
        // TODO add your handling code here:
        if((TFNama.getText().length() == 0)||
                (TFNama1.getText().length() == 0)||
                (TFAlamat.getText().length() == 0) || 
                (TFAlamat1.getText().length() == 0)||
                (TFTelp.getText().length() == 0)||
                (TFTelp1.getText().length() == 0)||
                (TFBerat.getText().length() == 0)||
                (TFBerat.getText().matches("[0]"))
                ){
            BTNProses.setEnabled(false);
        }
        else{
            BTNProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFAlamat1CaretUpdate

    private void TFBeratCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFBeratCaretUpdate
        // TODO add your handling code here:
        if((TFNama.getText().length() == 0)||
                (TFNama1.getText().length() == 0)||
                (TFAlamat.getText().length() == 0) || 
                (TFAlamat1.getText().length() == 0)||
                (TFTelp.getText().length() == 0)||
                (TFTelp1.getText().length() == 0)||
                (TFBerat.getText().length() == 0)||
                (TFBerat.getText().matches("[0]"))){
            BTNProses.setEnabled(false);
        }
        else{
            BTNProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFBeratCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TFNama.setText("");
        TFNama1.setText("");
        TFAlamat.setText("");
        TFAlamat1.setText("");
        TFTelp.setText("");
        TFTelp1.setText("");
        TFBerat.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void BTNUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUlangActionPerformed
        // TODO add your handling code here:
        TFNama.setText("");
        TFNama1.setText("");
        TFAlamat.setText("");
        TFAlamat1.setText("");
        TFTelp.setText("");
        TFTelp1.setText("");
        TFBerat.setText("");
        buttonGroup1.clearSelection();
        SDiskon.setValue(0);
        TAMonitor.setText("");
        BTNUlang.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BTNUlangActionPerformed

    private void BTNUlangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNUlangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BTNUlangMouseClicked

    private void BTNUlangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNUlangMousePressed
        // TODO add your handling code here:
        BTNUlang.setBackground(Color.red);
    }//GEN-LAST:event_BTNUlangMousePressed

    private void jBKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBKeluarMousePressed
        // TODO add your handling code here:
        jBKeluar.setBackground(Color.red);
    }//GEN-LAST:event_jBKeluarMousePressed

    private void jBHitungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBHitungMousePressed
        // TODO add your handling code here:
        jBHitung.setBackground(Color.red);
    }//GEN-LAST:event_jBHitungMousePressed

    private void jBAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAboutMousePressed
        // TODO add your handling code here:
        jBAbout.setBackground(Color.red);
    }//GEN-LAST:event_jBAboutMousePressed

    private void jBHitungMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBHitungMouseReleased
        // TODO add your handling code here:
        jBHitung.setBackground(Color.lightGray);
    }//GEN-LAST:event_jBHitungMouseReleased

    private void jBAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAboutMouseReleased
        // TODO add your handling code here:
        jBAbout.setBackground(Color.lightGray);
    }//GEN-LAST:event_jBAboutMouseReleased

    private void jBKeluarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBKeluarMouseReleased
        // TODO add your handling code here:
        jBKeluar.setBackground(Color.lightGray);
    }//GEN-LAST:event_jBKeluarMouseReleased

    private void TFNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNamaKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TFNamaKeyPressed

    private void TFNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNamaKeyReleased
        // TODO add your handling code here:
        jLNama.setForeground(Color.black);
    }//GEN-LAST:event_TFNamaKeyReleased

    private void TFTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelpKeyPressed
        // TODO add your handling code here:
        jLTelp.setForeground(Color.red);
    }//GEN-LAST:event_TFTelpKeyPressed

    private void TFTelpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelpKeyReleased
        // TODO add your handling code here:
        jLTelp.setForeground(Color.black);
    }//GEN-LAST:event_TFTelpKeyReleased

    private void TFAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAlamatKeyPressed
        // TODO add your handling code here:
        jLAlamat.setForeground(Color.red);
    }//GEN-LAST:event_TFAlamatKeyPressed

    private void TFNama1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNama1KeyPressed
        // TODO add your handling code here:
        jLNama1.setForeground(Color.red);
    }//GEN-LAST:event_TFNama1KeyPressed

    private void TFAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAlamatKeyReleased
        // TODO add your handling code here:
        jLAlamat.setForeground(Color.black);
    }//GEN-LAST:event_TFAlamatKeyReleased

    private void TFNama1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNama1KeyReleased
        // TODO add your handling code here:
        jLNama1.setForeground(Color.black);
    }//GEN-LAST:event_TFNama1KeyReleased

    private void TFTelp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelp1KeyPressed
        // TODO add your handling code here:
        jLTelp1.setForeground(Color.red);
    }//GEN-LAST:event_TFTelp1KeyPressed

    private void TFTelp1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelp1KeyReleased
        // TODO add your handling code here:
        jLTelp1.setForeground(Color.black);
    }//GEN-LAST:event_TFTelp1KeyReleased

    private void TFAlamat1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAlamat1KeyPressed
        // TODO add your handling code here:
        jLAlamat1.setForeground(Color.red);
    }//GEN-LAST:event_TFAlamat1KeyPressed

    private void TFAlamat1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAlamat1KeyReleased
        // TODO add your handling code here:
        jLAlamat1.setForeground(Color.black);
    }//GEN-LAST:event_TFAlamat1KeyReleased

    private void BTNProsesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNProsesMousePressed
        // TODO add your handling code here:
       BTNProses.setBackground(Color.red);
    }//GEN-LAST:event_BTNProsesMousePressed

    private void BTNProsesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNProsesMouseReleased
        // TODO add your handling code here:
        BTNProses.setBackground(Color.lightGray);
    }//GEN-LAST:event_BTNProsesMouseReleased

    private void TFNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNama1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPelanggan().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNProses;
    private javax.swing.JButton BTNUlang;
    private javax.swing.JLabel LPersen;
    private javax.swing.JRadioButton RBExpress;
    private javax.swing.JRadioButton RBReguler;
    private javax.swing.JSlider SDiskon;
    private javax.swing.JTextArea TAMonitor;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFAlamat1;
    private javax.swing.JTextField TFBerat;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNama1;
    private javax.swing.JTextField TFTelp;
    private javax.swing.JTextField TFTelp1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAbout;
    private javax.swing.JButton jBHitung;
    private javax.swing.JButton jBKeluar;
    private javax.swing.JLabel jLAlamat;
    private javax.swing.JLabel jLAlamat1;
    private javax.swing.JLabel jLBerat;
    private javax.swing.JLabel jLNama;
    private javax.swing.JLabel jLNama1;
    private javax.swing.JLabel jLTelp;
    private javax.swing.JLabel jLTelp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAbout;
    private javax.swing.JPanel jPBeranda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
