
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNPM = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfProdi = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfTelepon = new javax.swing.JTextField();
        tfCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NPM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prodi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        tfNPM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNPMKeyPressed(evt);
            }
        });
        getContentPane().add(tfNPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 63, 219, -1));

        tfNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNamaKeyPressed(evt);
            }
        });
        getContentPane().add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 94, 219, -1));

        tfProdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfProdiKeyPressed(evt);
            }
        });
        getContentPane().add(tfProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 125, 219, -1));

        tfAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAlamatKeyPressed(evt);
            }
        });
        getContentPane().add(tfAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 156, 219, -1));

        tfTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTeleponKeyPressed(evt);
            }
        });
        getContentPane().add(tfTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 187, 141, -1));

        tfCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodeKeyPressed(evt);
            }
        });
        getContentPane().add(tfCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 187, 38, -1));

        jLabel7.setText("--");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 20, -1));

        btnSimpan.setText("SIMPAN");
        btnSimpan.setBorder(new javax.swing.border.MatteBorder(null));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 218, 70, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Bebas Neue Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("DATA MAHASISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(tfNPM.getText().length()==0||tfNama.getText().length()==0||tfProdi.getText().length()==0||tfCode.getText().length()==0||tfTelepon.getText().length()==0)
        {
                   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
                   tfNPM.requestFocus();
                   return;
               }
        else{
        String nama = tfNama.getText();
        String NPM = tfNPM.getText();
        String prodi = tfProdi.getText();
        String alamat = tfAlamat.getText();
        String telp = tfTelepon.getText();
        String code = tfCode.getText();
        
        JOptionPane.showMessageDialog(null, "NPM \t\t: "+NPM+"\nNama\t: "+nama+"\nProdi\t: "+prodi+"\nAlamat\t: "+alamat+"\nNo. Telepon\t: "+code+telp);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tfNPMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNPMKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
               if(tfNPM.getText().length()==0){
                   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
                   tfNPM.requestFocus();
                   return;
               }
               btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_tfNPMKeyPressed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void tfNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
               if(tfNama.getText().length()==0){
                   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
                   tfNama.requestFocus();
                   return;
               }
               btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_tfNamaKeyPressed

    private void tfProdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProdiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
               if(tfProdi.getText().length()==0){
                   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
                   tfProdi.requestFocus();
                   return;
               }
               btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_tfProdiKeyPressed

    private void tfAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAlamatKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
               if(tfAlamat.getText().length()==0){
                   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
                   tfAlamat.requestFocus();
                   return;
               }
               btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_tfAlamatKeyPressed

    private void tfCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
               if(tfCode.getText().length()==0){
                   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
                   tfCode.requestFocus();
                   return;
               }
               btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_tfCodeKeyPressed

    private void tfTeleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTeleponKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
               if(tfTelepon.getText().length()==0){
                   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
                   tfTelepon.requestFocus();
                   return;
               }
               btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_tfTeleponKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfCode;
    private javax.swing.JTextField tfNPM;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfProdi;
    private javax.swing.JTextField tfTelepon;
    // End of variables declaration//GEN-END:variables
}
